# -*- coding: utf-8 -*-
"""PerplexityMetric.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i7QlzKwIQoWRNNPlQLt04q8fEAIKe8Yw
"""

from transformers import GPT2LMHeadModel, GPT2Tokenizer
import torch

class PerplexityCalculator:
    def __init__(self, text, model, tokenizer):
        self.text = text
        self.model = model
        self.tokenizer = tokenizer

    def get_perplexity(self):
        inputs = self.tokenizer(self.text, return_tensors='pt')
        with torch.no_grad():
            outputs = self.model(**inputs, labels=inputs["input_ids"])
            loss = outputs.loss
            perplexity = torch.exp(loss).item()
        return perplexity

    def check_perplexity(self):
        perplexity = self.get_perplexity()

        if perplexity <= 20:
            return "Model is good"
        elif 20 < perplexity < 50:
            return "Model is medium"
        elif perplexity >= 50:
            return "Model is bad"